blank_issues_enabled: false
contact_links:
  - name: leaf Discord discussion
    url: https://discord.gg/leaf-oss
    about: Please ask and answer questions here.
  - name: Report a security vulnerability
    url: https://github_com_block_leaf_placeholder/security/policy
    about: Please report security vulnerabilities here.
